### ISSUE TITLE
Does the example work?

### ISSUE THREAD

**Issue by cronoklee** [reedsy/quill-cursors#11]
Downloading the zip and opening `index.html` throws a load of errors, presumably because Quill is missing...
![image](https://user-images.githubusercontent.com/8842685/42127483-74cbad74-7c91-11e8-825c-97cf8fa8cf95.png)

However on inspection of `examples/index.html` there are multiple references to files which are not in the Quill repo either.
`quill-cursors.min.js`, `quill-cursors.css`, etc

Can you guys add some explanation of how to view the demo and perhaps a link to an online version?

**Comment by Jbithell** [comment]
You have to include Quill itself first - I did that by placing the following in my example file
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css" integrity="sha256-oSrCnRYXvHG31SBifqP2PM1uje7SJUyX0nTwO2RJV54=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.snow.min.css" integrity="sha256-qc/vMbPSg7/JfxMwKeMv3wlx7ojG33FXfYfO0UJIsc0=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.min.js" integrity="sha256-3oYBiGm16EW9wQH8G1VhGh43XgivbO5KaB10RhA9phE=" crossorigin="anonymous"></script>
    
```

As for this repo itself - you have to build it yourself first to use it unfortunately. I've build the latest revision and attached it if that helps!


[quill-cursors.zip](https://github.com/reedsy/quill-cursors/files/2331473/quill-cursors.zip)

**Comment by mccoysc** [comment]
<script src="./quill.js"></script>
<link href="./quill.snow.css" rel="stylesheet">
<link href="./quill.bubble.css" rel="stylesheet">


<script src="./quill-cursors.js"></script>
<link href="./quill-cursors.css" rel="stylesheet">


<script src="./y.js"></script>

QuillCursors is alway undefined
@Jbithell

**Comment by mccoysc** [comment]
[yjs.zip](https://github.com/reedsy/quill-cursors/files/2612255/yjs.zip)

**Comment by alecgibson** [comment]
Yes, to run the example, you have to clone the repo, and then run:

```bash
npm install
npm start
```

The current built file can be found on the releases page: https://github.com/reedsy/quill-cursors/releases/tag/v2.0.2
