### ISSUE TITLE
Scrolling ruins the selection

### ISSUE THREAD

**Issue by RobbinBaauw** [reedsy/quill-cursors#14]
Hi,

I'm trying to implement this plugin and it seems fine, but for one thing. Upon scrolling, the selection doesn't go with the scroll. I've attached some images.

It seems to be because the selection block has a "top" attribute, which doesn't update, even though the rest of the page does update. As the top is relative to the Quill container, the scrolling doesn't update the selection (as the Quill container doesn't move).

Do you know a solution? I can try to fix it myself as well, if this is not a known problem.

Perhaps something can be done like in the tooltip code: https://github.com/quilljs/quill/blob/9a77567fe356d384074df7479c33ceac509d9351/ui/tooltip.js

Before scrolling: https://imgur.com/a/4cNTG4k
After scrolling: https://imgur.com/a/tnWbA1E

Edit: created a PR https://github.com/reedsy/quill-cursors/pull/15

**Comment by alecgibson** [comment]
@RobbinBaauw we've just released a major version bump. Can you please try again? I've tested the example in Chrome on macOS and scrolling seems fine.

If you still find it's broken, can you please provide:
 - browser
 - OS
 - a reproducible case (preferably in a JSFiddle or similar)

**Comment by RobbinBaauw** [comment]
Hey, I've tried it and I think I know what the problem is.

It seems to work until I add a custom toolbar (which I did in my project). I have a codepen here: https://codepen.io/robbinbaauw/pen/JwpyRv.

As you see, when the quill container itself scrolls, it doesn't work anymore. I think the fix I had would still apply (albeit in a different form).

**Comment by alecgibson** [comment]
Aha I see what you mean. I can replicate this in the example if I fix the height of the Quill editor. Also, I've noticed a related bug, whereby the selection shows outside of Quill.

<img width="1277" alt="screen shot 2019-02-27 at 07 33 23" src="https://user-images.githubusercontent.com/12036746/53473406-33b1b100-3a62-11e9-91bc-82f210b624bb.png">

**Comment by alecgibson** [comment]
@RobbinBaauw I've put together a PR that's slightly simpler than yours https://github.com/reedsy/quill-cursors/pull/21

Can you please try it out and see if it solves your issue?

Here's the bundled JS in case you need it: [quill-cursors.js.zip](https://github.com/reedsy/quill-cursors/files/2909574/quill-cursors.js.zip)

**Comment by RobbinBaauw** [comment]
Yes it works! Closing my PR now
