### ISSUE TITLE
Selection display is delayed after format change

### ISSUE THREAD

**Issue by mitar** [reedsy/quill-cursors#2]
If I select part of the text and click "bold", the other user sees bold change immediately, but the selection disappears for a bit before it reappears

Tested on https://quill-sharedb-cursors.herokuapp.com/

![untitled](https://user-images.githubusercontent.com/585279/27172140-02dbeebc-5169-11e7-8951-abd063191e42.gif)

**Comment by pedrosanta** [comment]
Yikes, thank you @mitar, I'll debug and fix as soon as I can. 🙂

Cheers, thanks for spotting this one!

**Comment by mitar** [comment]
Thanks for explanation!
