### ISSUE TITLE
npm install quill-cursors --save error

### ISSUE THREAD

**Issue by jhinkel** [reedsy/quill-cursors#27]
I'm trying to integrate multiple-cursors into quilljs, and would love to be able to do this!  However, when I try to install with npm, it gives me an error that says CERT_UNTRUSTED... please advise!

**Comment by alecgibson** [comment]
@jhinkel could you please paste the whole output from your console?

**Comment by jhinkel** [comment]
Sure!  Console output is below:

`npm http GET https://registry.npmjs.org/quill-cursors
npm http GET https://registry.npmjs.org/quill-cursors
npm http GET https://registry.npmjs.org/quill-cursors
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-141-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "quill-cursors" "--save"
npm ERR! cwd /var/www/html/quillRT
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/html/quillRT/npm-debug.log
npm ERR! not ok code 0
`

**Comment by alecgibson** [comment]
For starters, I'd try updating both `npm` and `node`. There have been several major version bumps since the versions you're running, and Node v0 stopped LTS a while ago.

**Comment by jhinkel** [comment]
turned out it was about how node was interacting with my ssl... Thanks for the help!  Closing
