### ISSUE TITLE
Bug with code when wrapped with electron

### ISSUE THREAD

**Issue by jefflam** [reedsy/quill-cursors#3]
Hi!

Just want to write a note of thanks on this great module, helped greatly with a project :)

Discovered a bug that has to do with one of the javascript functions that is not supported across all browsers/chromium.

In cursors.js, line 88:

`
CursorsModule.prototype.update = function() {
  Object.values(this.cursors).forEach(this._updateCursor.bind(this));
};
`

`Object.values` will result in an error when it is run in the chromium version of an electron wrapped app. This function would be the same if you simply change the function to this:

`
CursorsModule.prototype.update = function() {
  Object.keys(this.cursors).map((key) => {
    this._updateCursor(this.cursors[key])
  })
};
`

Just thought to share and hope you can apply the change!

**Comment by pedrosanta** [comment]
Hi @jefflam,

Hey, thanks, glad to hear that. 🙂 👍 

I see. I'll update, release a new version and ping ya! Thanks for sending in the solution, it really helps.

Cheers.

**Comment by jefflam** [comment]
No problem and thanks!

**Comment by pedrosanta** [comment]
@jefflam Just published `0.1.7` with this fixed. Cheers!
