### ISSUE TITLE
Make tooltip delay configurable

### ISSUE THREAD

**Issue by mitar** [reedsy/quill-cursors#4]
I like how hovering over the tooltip shows the name like in Google Docs. But I feel it stays visible a bit too long. Maybe the delay could be configurable? Personally, I would make it so that it disappears when you go away from the cursor with your mouse.

**Comment by pedrosanta** [comment]
Hey @mitar, this makes much sense and I think it should be easily doable.

I'll ping ya when I release a new version with this. 🙂 👍

**Comment by pedrosanta** [comment]
Hi @mitar! Just published `0.1.7` with this added. Cheers!

**Comment by mitar** [comment]
Cool!

Hm. It seems that hiding always happens, not only on mouseout from the cursor? I thought that there is a delay after a moveout, but if I am still on it, it will stay available?

**Comment by pedrosanta** [comment]
Hi @mitar, yep, there seems to be some issue with that. I'll update to consider the hover as a whole.

**Comment by pedrosanta** [comment]
Just fixed this on `1.0.2` @mitar. Cheers!
