### ISSUE TITLE
import blocked due to disallowed mime type text/html...

### ISSUE THREAD

**Issue by jhinkel** [reedsy/quill-cursors#40]
when I type "include './quill-cursors' ", it seems to find the quill-cursors module on my server just fine, but my server seems to recognize the module as text/html and doesn't load it because of a disallowed mime type.  Is quill-cursors referring to the ts files in the directory?  If so, what mime type should those have?  Trying to configure my server correctly

**Comment by alecgibson** [comment]
The actual error output is always useful.

**Comment by jhinkel** [comment]
from the firefox console:

Loading module from “[my server url]/quill-cursors” was blocked because of a disallowed MIME type (“text/html”).
quillRT
Loading failed for the module with source “[my server url]/quill-cursors".

from the chrome console:

Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by alecgibson** [comment]
Are you forgetting the file extension?

**Comment by jhinkel** [comment]
I shouldn't be.... the readme says that

`import QuillCursors from 'quill-cursors';`

is the correct syntax.  However, it didn't recognize the filepath until I used ./quill-cursors

**Comment by alecgibson** [comment]
Can you please post a minimal working example?

**Comment by jhinkel** [comment]
I can't because the import mime type error is halting all the other code from running:  see johnhinkel.com/quillRT

**Comment by alecgibson** [comment]
You shouldn't be importing it like that in inlined JavaScript. When you're writing in HTML, you should follow the HTML import example:

```javascript
<script src="quill-cursors.js"></script>
```

Where obviously you'll need to update `src` to point to wherever it is you're hosting the package.

**Comment by jhinkel** [comment]
ok, well it still says the script didn't load due to disallowed mime type:
`
The script from “URL/quill-cursors.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
quillRT
The script from “URL/quill-cursors.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
quillRT
Loading failed for the <script> with source “URL/quill-cursors.js”.
`

however, they're warnings instead of errors this time

**Comment by jhinkel** [comment]
@alecgibson not closed because my initial question wasn't answered....

"Is quill-cursors referring to the ts files in the directory? If so, what mime type should those have? Trying to configure my server correctly"

**Comment by jhinkel** [comment]
something's still wrong because when I try to register QuillCursors, it says that QuillCursors is not defined

**Comment by alecgibson** [comment]
You might be missing the `type` attribute from your `script` tag:

```javascript
<script src="quill-cursors.js" type="text/javascript"></script>
```

I'll update the docs, but to be honest walking people through how to include JavaScript files in their project is a bit beyond the scope of this package.

**Comment by jhinkel** [comment]
no need to act holier-than-thou about it.  When you write a package, from a usability standpoint, the README should contain everything necessary for anyone (of any level of experience) to get your package working.  That way you aren't limiting your user base to just people that are javascript experts.

**Comment by jhinkel** [comment]
and your solution of adding type="text/javascipt" changed nothing

**Comment by alecgibson** [comment]
Have you tried clicking on the route the `src` tag takes you to? ie https://johnhinkel.com/quillRT/quill-cursors.js

You'll see that you get a `404`. I recommend you fix your reference.

**Comment by jhinkel** [comment]
you were the one that told me to add the .js in the first place.  I assumed it was already in the quill-cursors directory since you were the one telling me to add it.  when I just use https://johnhinkel.com/quillRT/quill-cursors, that resolves just fine but causes other errors since it's a directory and not a file.  What is the correct file in the quill-cursors package to put in the src for that script tag?

**Comment by alecgibson** [comment]
Then you need to update this to point at the actual JavaScript file:

```javascript
<script src="./quill-cursors/dist/quill-cursors.js"></script>
```

**Comment by jhinkel** [comment]
That did it!  Thanks for your help, and in the future, when you're helping someone else out, consider the clarity of your instructions before saying that "walking people through how to include JavaScript files in their project" like I'm some sort of remedial programmer is the pain point

**Comment by alecgibson** [comment]
You're welcome. Unfortunately in this day and age of all multitudes of module bundlers, transpilers, etc., where everyone has a slightly different build setup, it's basically impossible to write fool-proof, generic documentation to that level of detail and we have to assume some level of knowledge.

**Comment by jhinkel** [comment]
Completely understood.  However, you have to be willing, then, to answer questions about people's individual setups without prematurely closing the ticket the way you did... Just a heads up about how to deliver better customer service... I really like quill and want it to succeed, but it won't if you provide customer service like this

**Comment by alecgibson** [comment]
For the record, I'm not a part of Quill (so whatever bad thoughts you have, please direct them at me, not them).

**Comment by jhinkel** [comment]
Fair enough.  Thanks again for the help.  You helped me solve a big problem I was having for my client

**Comment by pedrosanta** [comment]
@jhinkel I just want to point out that this is an Open Source collaborative project where people and companies wholeheartedly contribute and share their time and effort for the benefit of all, and although the contributors make an effort to have the operational level of this package at it's best possible, and give support to it completely free—as well as the package—one shouldn't expect from this package the service level of paid and commercial services—those do have customers and customer support.

**Comment by AlejandroVaqueraLopez** [comment]
I solved the problem by (just adding the proxy_pass http://localhost:port;) cause an app that uses a port in your droplet, is globally running in it, so, you don't need to specify where you have the files of that proyect. just point to the port of that app. It worked perfectly and did no more problems. If you have questions, please reply to this, I will help if I can.
