### ISSUE TITLE
setStart error

### ISSUE THREAD

**Issue by houshuang** [reedsy/quill-cursors#42]
We've been getting a number of errors from Rollbar like this:

```js
IndexSizeError: Failed to execute 'setStart' on 'Range': There is no child at offset 1. (Most recent call first)
```

They all come from quill-cursors.ts:191

```js
a.setStart(n[0].domNode, n[1]), a.setEnd(o[0].domNode, o[1]);
```

It seems that all the errors are generated by Electron 3 on Windows. However, it seems to me that the setRange functionality should be well supported by Electron 3. This is happening in our fork (but we made very few changes). It might of course be related to something we're doing, but if you have any ideas on how to investigate or solve this, I'd appreciate it!

Backtrace:
```js
File ../node_modules/@minervaproject/quill-cursors/dist/quill-cursors.js line 225 col 1 in e._updateCursor
a.setStart(n[0].domNode, n[1]), a.setEnd(o[0].domNode, o[1]);
File ../node_modules/@minervaproject/quill-cursors/dist/quill-cursors.js line 170 col 1 in e.moveCursor
r && (r.range = e, this._updateCursor(r));
File components/BlockComponent/RichTextField.js line 96 col 21 in [anonymous]
cursors.moveCursor(userId, { index: min, length: len });
File components/BlockComponent/RichTextField.js line 62 col 15 in u.<anonymous>
srcList.forEach((src) => {
File ../node_modules/events/events.js line 142 col 1 in u.emit
ReflectApply(listeners[i], this, args);
File ../node_modules/@teamwork/sharedb/lib/client/doc.js line 1474 col 1 in [anonymous]
doc.emit('presence', srcList, submitted);
File ../node_modules/process/browser.js line 167 col 1 in d.run
this.fun.apply(null, this.array);
File ../node_modules/process/browser.js line 131 col 1 in drainQueue
currentQueue[queueIndex].run();
```

**Comment by alecgibson** [comment]
Can you please provide a minimal working example?

**Comment by houshuang** [comment]
Unfortunately I haven't been able to reproduce it, however from Rollbar I can tell that it usually tends to happen to multiple members of the same group at the same time. Loading the same document gives me no problems, so it must be a result of certain presence updates, however since presence updates aren't persisted, it's hard to reproduce. 

I have upgraded to the latest version of quill-cursors, where some of the logic around handling selection ranges has changed, so I will wait to see if the problem persists.

**Comment by alecgibson** [comment]
I've just deployed a minor version bump, which rewrites how we handle multi-line ranges. I'm going to close this due to inactivity. Please re-open if you can get a reproducible set of steps.
