### ISSUE TITLE
Using with react-quill, cursors stays hidden

### ISSUE THREAD

**Issue by FriendlyPigeon** [reedsy/quill-cursors#44]
I am using this module with react-quill and managed to get it working with a reference, I see the cursors objects in the editor by inspecting the DOM. However, when I run moveCursor the cursors stay hidden afterwards and I never see the cursors.

```javascript
  componentDidMount() {
    this.attachQuillRefs();
    
    cursorsObject = this.quillRef.getModule('cursors')
    
    socket.on('editorContent', (editorContent) => {
      this.setState({ text: editorContent.content })
    })
    
    socket.on('cursorMove', (cursor) => {
      cursorsObject.moveCursor(cursor.user, cursor.cursorRange)
    })
    
    socket.on('usersChanged', (userInformation) => {
      if(userInformation.action === 'joined') {
        cursorsObject.createCursor(userInformation.user, 'User '+userInformation.user, 'blue');
      } else if(userInformation.action === 'quit') {
        cursorsObject.removeCursor(userInformation.user)
      }
    })
  }
```
![chrome_DFluQJl2ny](https://user-images.githubusercontent.com/24982474/68917126-20e12880-0726-11ea-9c70-4f705e520ef9.png)

**Comment by alecgibson** [comment]
Can you please provide a minimal working example? (Preferably as a repo). A first guess is that `cursor.cursorRange` may not be a valid Quill range.

**Comment by FriendlyPigeon** [comment]
@alecgibson that was exactly the issue. On the server side I took in cursorRange: range and was sending out cursor instead of cursor.cursorRange, so I just changed the socket to emit cursor.cursorRange instead of just cursor. Thanks for the help!
