### ISSUE TITLE
ql-cursor-selections span renders `null` (text) on Edge browser

### ISSUE THREAD

**Issue by harrisonlo** [reedsy/quill-cursors#45]
When cursor selected text:

![image](https://user-images.githubusercontent.com/7886751/72239984-b103f700-361d-11ea-8f6e-8c177ea38ea5.png)

UI:

![image](https://user-images.githubusercontent.com/7886751/72240043-d7299700-361d-11ea-80cd-d9356be8716f.png)

With cursor not selecting anything (but focused, so range length is 0):

![image](https://user-images.githubusercontent.com/7886751/72240076-f9231980-361d-11ea-8148-493968013874.png)

UI:

![image](https://user-images.githubusercontent.com/7886751/72240091-06400880-361e-11ea-8a7b-158f1c250919.png)

Only on Edge browser, which is kinda growing in market share (more users than Safari)

Any idea where that text came from?

**Comment by alecgibson** [comment]
@harrisonlo Thanks for the bug report! Please let me know if the latest release doesn't resolve your issue.

**Comment by harrisonlo** [comment]
Woah that was fast! Thank you for the awesome work!
