### ISSUE TITLE
Quill does not show multiple cursors until editor is focused

### ISSUE THREAD

**Issue by sferoze** [reedsy/quill-cursors#5]
If I load a document that is currently being edited by someone else, I see text added to the document by the other person but the cursor does not show. 

The element ql-cursors is empty so the cursor has not been built yet. 

But as soon as I focus the editor, the cursor is built and appears correctly. 

How come the other person cursor only shows once the document is first focused? Once the document is focused, and if it is blurred, the cursor still shows. So it really only requires an initial focus for the cursor to appear.

**Comment by pedrosanta** [comment]
Hi @sferoze,

Where do you see that behaviour happening? In this module example? Or another implementation?

As it's said in the README and looking at the API, this module is solely focused on properly drawing and shifting the cursors upon changes on the text. So, one would still have to add the proper connections sync and handling code – including the part to draw/set cursors for all the active connections received from an upstream server responsible for handling the sync of cursors/connections. As it says on README:

> - You should implement some sort of server-side code/API (or another suitable mechanism) to maintain cursors information synced across clients/Quill instances;
> - This module is responsible for automatically updating the cursors configured on the module when there is a 'text-change' event - so if the client/instance contents are updated locally or through a updateContents() call, one shouldn't be needing to do anything to update/shift the displayed cursors;
> - It is expected for the clients/instances to send updated cursor/range information on selection-change events;​
> - Additionally, the client code should guarantee:
>   - The drawing the initial cursors for all the active connections at init;
>   - Updating a cursor with move/set when an cursor update is received;
>   - Calling remove cursor when receiving a cursor/client disconnection;

You can also check how this is being handled on the reference implementation I've published over at https://github.com/pedrosanta/quill-sharedb-cursors.

Hope it helps. Cheers!
