### ISSUE TITLE
Incorrect positioning of cursors inside css transformed quill

### ISSUE THREAD

**Issue by manstie** [reedsy/quill-cursors#59]
How to reproduce:

1. go to https://jsfiddle.net/mpdjea7f/
2. type into User 1 box, highlight a word
3. See in User 2 box, the cursor position and selection are offset.

There is an issue with positioning when a div or any parent div has a css `transform` rotate/scale.

**Comment by alecgibson** [comment]
What's your use-case here?

**Comment by manstie** [comment]
We allow users to scale, rotate and translate text areas.

**Comment by alecgibson** [comment]
Okay, this is a bit outside the original scope for this library, and I'm not sure I've got time to work on this, but a pull request would be more than welcome!

**Comment by alecgibson** [comment]
What's wrong with applying your `transform` to `.ql-editor` instead of `.ql-container`?

See updated example: https://jsfiddle.net/alecgibson/o3ut2m5w/1/

**Comment by manstie** [comment]
Interesting, I hadn't tried that. I'll see what I can do.

**Comment by manstie** [comment]
So the way to get an element's dimensions before a css transform is using `offsetLeft`, `offsetTop`, `offsetWidth`, and `offsetHeight`. But it's only for `HTMLElement`s and since there is no way to get these properties for a `Range` or text node, there would have to be some 'hack' put in place, either:
1. undo the transform, calculate, then re-transform
2. display a transformed 'mirror' like in http://edg2s.github.io/rangefix/
3. create spans in-place and put the range inside them then get the HTMLElement's properties

Since there's no nice way to fix this I have opted with working around my current system to transform just the editor.

I am happy for this issue to be closed. Thanks.

**Comment by alecgibson** [comment]
Great. Glad you got it solved!
