### ISSUE TITLE
Cannot read property 'getClientRects' of undefined

### ISSUE THREAD

**Issue by dennislaupman** [reedsy/quill-cursors#6]
Hello,

I get a fatal error when running the example code

![image](https://user-images.githubusercontent.com/1274858/29527309-bf19ec3c-8698-11e7-865b-887937068117.png)

Node module is installed but not loaded into de document. 
If I include:
<script src="rangefix.js"></script>

It's works fine

Grtz Dennis

**Comment by pedrosanta** [comment]
Hi @dennislaupman, I think this has since been fixed.

Could you try out with the latest release?

Cheers.
