### ISSUE TITLE
Broken non-minified dist version

### ISSUE THREAD

**Issue by pedrosanta** [reedsy/quill-cursors#7]
So, noticed earlier that when trying to use the non-minified version of this module (`/dist/quill-cursors.js`) on the included example, it doesn't run and displays the following error:

```
TypeError: undefined is not an object (evaluating 'target.register') (...)
```

I think this has to do to some issue with Webpack bundling, but still haven't found out why.

**Comment by jeffbryner** [comment]
Can 2nd this. When trying to import the non-minified version I get the same error. Importing the min.js version works: 
In my meteor project I need to do: 
const QuillCursors=require('quill-cursors/dist/quill-cursors.min.js');

then 
    Quill.register('modules/cursors', QuillCursors);
    Quill.import('modules/cursors')
to have it all work out properly

**Comment by alecgibson** [comment]
This should now be fixed in the latest version.
