### ISSUE TITLE
Other user's cursor position prevents clicking on link text. 

### ISSUE THREAD

**Issue by vivek-eraser** [reedsy/quill-cursors#72]
This is similar to [this](https://github.com/reedsy/quill-cursors/issues/32) issue. The other user's cursor position prevents clicking on the link text via the cursor.

**Comment by alecgibson** [comment]
I'm not entirely sure I understand the issue. Do you mean if you happen to click exactly on a user's cursor then it doesn't open the link? Presumably it works fine if you click either side of the cursor, right?

Could you please provide exact repro steps, and preferably a screen capture?

**Comment by vivek-eraser** [comment]
You are right about clicking on the either side but I do feel that it is not a good user experience. Please find below the attached screen capture.

[Issue](https://user-images.githubusercontent.com/74950798/150868646-7bf246d3-307e-4cf3-9d74-345ffaddd0b8.mp4)

**Comment by alecgibson** [comment]
I agree that's not great; just wanted to clarify what problem we're solving — thanks for the recording!
