### ISSUE TITLE
Engine requirement

### ISSUE THREAD

**Issue by pyrocat101** [reedsy/quill-cursors#78]
Is there a reason that this library limits engine version to 14.x? I was trying it on Node 17.x and yarn refuses to install without `--ignore-engines`.

The library itself runs in the browser, so I assume the engine version is only for development (e.g. running tests). Can we relax the engine requirement here?

**Comment by alecgibson** [comment]
Released in `3.1.2`

**Comment by pyrocat101** [comment]
Thank you!
