### ISSUE TITLE
QuillCursors.prototype._applyDelta needs improvement

### ISSUE THREAD

**Issue by pedrosanta** [reedsy/quill-cursors#8]
Noticed a few things, that end up being caught on the `QuillCursors.prototype._updateCursor` 'sanity check' when one's editing a document, namely with insert and delete operations around other people selections:

- When one deletes the whole first line of text when another user cursor is in the middle of it – that user cursor is going to be 'shifted backwards' by the amount of the delete/the whole line length and will have a negative index afterwards;
- When module receives a delete op that 'touches' another user active selection;

All these tweaks and improvements should be done after a look into how other collaborative text editors (Google Docs, etc.) handle other users selections when editing content close/near/inside these.

**Comment by alecgibson** [comment]
This whole function has been removed in the latest breaking change.
