### ISSUE TITLE
Newlines in html template in minified js?

### ISSUE THREAD

**Issue by IvanVolons** [reedsy/quill-cursors#84]
Downloading 3.1.2 from NPM (and other versions as far as I can tell) seems to contain newlines in the html template used for displaying the cursor flag. These newlines render and make it appear as though there is a lot of padding around the name.

I narrowed it down to this minified code:
`o='\n  <span class="'.concat(i.default.SELECTION_CLASS,'"></span>\n  <span class="').concat(i.default.CARET_CONTAINER_CLASS,'">\n    <span class="').concat(i.default.CARET_CLASS,'"></span>\n  </span>\n  <div class="').concat(i.default.FLAG_CLASS,'">\n    <small class="').concat(i.default.NAME_CLASS,'"></small>\n  </div>\n');`

When I remove the newlines from that minified code, everything renders quite well. Seems like this is unintentional.

Attached image of how it looks (with text selected highlighting the newline). Let me know if I'm just missing something!
![image](https://user-images.githubusercontent.com/11995126/178904887-0fe9629f-08b7-45c8-b4ad-e6ab0cdd47c4.png)

**Comment by fyvfyv** [comment]
@alecgibson I can take it after the previous 2 issues.  It won't be soon

**Comment by IvanVolons** [comment]
Thanks for the quick reply! I believe the issue might be with webpack (I saw [this](https://stackoverflow.com/questions/57524832/how-to-remove-n-and-t-from-webpack-compiled-template-literal) issue that seemed similar) and I noticed there were some recent changes related to webpack, so maybe this broke at that time?

Regardless, I think the simplest way to fix this would be to follow this solution https://stackoverflow.com/a/37321145 and add "line continuation" characters at the end of each line in https://github.com/reedsy/quill-cursors/blob/main/src/quill-cursors/template.ts

I can make a PR for that if you like although I don't know how to build/test the module with that change in place

**Comment by alecgibson** [comment]
@IvanVolons I'm not sure I understand the issue. Whitespace should be [collapsed by the browser](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace), so newlines in the source code shouldn't matter, unless you've set something like [`white-space: pre;`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#pre)?

Can you please check the `white-space` value of that DOM node, and report back? It should be set (by this library) to [`nowrap`](https://github.com/reedsy/quill-cursors/blob/948228587299ebb5f4b036e213acb625dc86d643/assets/quill-cursors.scss#L90). If that looks normal, let us know which browser you're using, and please provide an MWE.
