### ISSUE TITLE
Unable to Build Project With Quill-Cursors imported

### ISSUE THREAD

**Issue by Chaddeus** [reedsy/quill-cursors#85]
Hello, I'm attempting to use quill-cursors in a SvelteKit project, using TypeScript, and when I build the project, Vite is showing this error:

`ReferenceError: self is not defined
    at Object.<anonymous> (/.../node_modules/quill-cursors/dist/quill-cursors.js:2:206)`

**Comment by alecgibson** [comment]
Could you please provide a minimal working example?

**Comment by Chaddeus** [comment]
I apologize for the delay. I have since moved on and will be implementing TipTap in my app. I appreciate the response. 🙏
