### ISSUE TITLE
Can't get cursors to show up no matter what

### ISSUE THREAD

**Issue by robmpreston** [reedsy/quill-cursors#9]
Clearly doing something wrong but  can't figure out what. 

I'm calling:
Quill.register('modules/cursors', QuillCursors)

These are my options:
`{`
`        modules: {`
`         cursors: {`
`            autoRegisterListener: false`
`          },`
`          history: {`
`            userOnly: true`
`          },`
`          toolbar: true`
`        },`
`        placeholder: this.placeholder,`
`        theme: 'snow'`
`      }`

I have collaborative editing setup, that all works fine. I keep track of the connections and cursor positions and update the cursors with them, and if I inspect the data it all looks right:

<img width="553" alt="screen shot 2018-03-11 at 10 08 33 pm" src="https://user-images.githubusercontent.com/9950092/37262458-949a670e-2579-11e8-80a8-536bf4d6073a.png">

As you can see in that picture, the cursor is inserted and the data all looks correct, but nothing renders on the editor.

I've also tried manually inserting cursors with dummy data and nothing shows.

Is there some styling that needs to be included that I'm missing? Been messing with this for 3 days now and can't figure it out.

**Comment by pedrosanta** [comment]
Hi @robmpreston,

Yes, you do have to include the `dist/quill-cursors.css` if you want them to work.

You can also pick those classes up to customize the cursors, if you wish.

Cheers! 🙌
