### ISSUE TITLE
Event listeners should be passive

### ISSUE THREAD

**Issue by Didi3333** [reedsy/quill-cursors#92]
Hi,

I updated my program to Quill 2.0.2 and now i have a wargning in console about:

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event

![image](https://github.com/reedsy/quill-cursors/assets/32233417/77577aba-dfd7-48b6-bc4e-c559027c6c26)

Regards

**Comment by alecgibson** [comment]
Released in v4.0.3
