### ISSUE TITLE
Text and selection changes across network

### ISSUE THREAD

**Issue by navadev** [reedsy/quill-cursors#94]
Hello, I'm new to Quill and Quill Cursors.

Looking at the example, I can see that the range is being used to update the cursor and the delta is being used to update the other's Quill editor state.

1. Is there a recommended way to send this info across the network to update state on a remote Quill editor? (Maybe [Delta import](https://quilljs.com/docs/api#import) and [maybe serialized Range](https://quilljs.com/docs/api#getselection))? 
2. Does quill-cursors handle handle concurrent updates (a la [ProseMirror](https://marijnhaverbeke.nl/blog/collaborative-editing.html)) or does it leave this up to the user? From the example, it seems the latter might be the case, but I just want to confirm.

**Comment by alecgibson** [comment]
Quill cursors is hands-off about updates, and leaves this as an exercise to whatever library you're using to handle text changes in general. For example ShareDB has a [Presence system](https://share.github.io/sharedb/presence) that can be used to sync cursors.

I did [a lot of work](https://github.com/share/sharedb/pull/322) on this in ShareDB, and realised that it's a sufficiently complicated problem that Quill Cursors cannot do a good job of this itself, without more information about the real-time updates. Therefore, this is left up to the syncing library.

**Comment by navadev** [comment]
Thank you very much for the clarification @alecgibson.

**Comment by pedrosanta** [comment]
> Quill cursors is hands-off about updates and leaves this as an exercise to whatever library you're using to handle text changes in general. For example, ShareDB has a [Presence system](https://share.github.io/sharedb/presence) that can be used to sync cursors.
> 
> I did [a lot of work](https://github.com/share/sharedb/pull/322) on this in ShareDB, and realized that it's a sufficiently complicated problem that Quill Cursors cannot do a good job of this itself, without more information about the real-time updates. Therefore, this is left up to the syncing library.

@alecgibson is pretty much on point here. Before his work on ShareDB the cursor sync was experimental at best. Any cursor sync that was out-of-arrival-sync with actual document OT operations data/events would eventually lead to state inconsistencies.

Transient presence data (of any sync system) is definitely what one should look at for this.
